# Generated by Django 4.2 on 2023-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/users/images/default_user_avatar.jpg', upload_to='static/users/images/user_profile_images', verbose_name='Фотография'),
        ),
    ]
