# Generated by Django 4.2 on 2023-06-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_login_time',
            new_name='last_online',
        ),
    ]
