# Generated by Django 4.2 on 2023-06-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_last_login_time_customuser_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего входа'),
        ),
    ]
