# Generated by Django 4.2 on 2023-06-12 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_last_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='id устройства'),
        ),
    ]
