# Generated by Django 4.2 on 2023-06-12 11:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_connectionhistory_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='id устройства'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.DeleteModel(
            name='ConnectionHistory',
        ),
    ]
