# Generated by Django 4.2 on 2023-06-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_device_id_customuser_last_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_online',
        ),
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='id устройства')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего входа')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
