# Generated by Django 4.2 on 2023-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionhistory',
            options={'verbose_name': 'История подключений', 'verbose_name_plural': 'Истории подключений'},
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='last_online',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего входа'),
        ),
    ]
