# Generated by Django 4.2 on 2023-06-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_connectionhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionhistory',
            old_name='status',
            new_name='online_status',
        ),
    ]
