# Generated by Django 4.2.3 on 2023-07-16 07:52

import django.core.validators
from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/users/images/user_profile_images/default_user_avatar.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1024, 1024], upload_to=users.models.get_user_image_path, validators=[django.core.validators.FileExtensionValidator(['JPEG', 'PNG', 'SVG']), users.models.validate_file_size], verbose_name='Фотография'),
        ),
    ]
