# Generated by Django 4.2.3 on 2023-07-23 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectionhistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
