# Generated by Django 4.2.3 on 2023-07-26 12:29

import django.core.validators
from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_connectionhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='/users/images/user_profile_background_images/default_user_profile_bg_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=users.models.get_user_image_path, validators=[django.core.validators.FileExtensionValidator(['JPEG', 'JPG', 'PNG', 'SVG']), users.models.validate_file_size], verbose_name='Фоновое изображение'),
        ),
    ]
