# Generated by Django 4.2.3 on 2023-07-29 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
