# Generated by Django 4.2.3 on 2023-08-14 14:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_post_options_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_post_image_path, verbose_name='Изображение поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Текст поста'),
        ),
    ]
