# Generated by Django 4.2.3 on 2023-08-14 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_post_image_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 43, 44, 622879, tzinfo=datetime.timezone.utc), verbose_name='Время создания'),
        ),
    ]
