# Generated by Django 4.2.3 on 2023-07-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
