# Generated by Django 4.2.3 on 2023-07-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
